name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v4

      - name: Check CMake version
        run: cmake --version

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Generate CMake project
        run: cmake -S. -Bbuild -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CONFIGURATION_TYPES=Release

      - name: Build 64bit release DLL
        run: cmake --build build --config Release --target ALL_BUILD

      - name: Rename DLL to BadAPI-dev-{GITHUB_SHA}.dll
        run: ren BadAPI.dll BadAPI-dev-${{github.sha}}.dll
        working-directory: build/Release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-Clang
          path: build/Release/BadAPI-dev-*.dll
